services:
    - docker

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
    - image="mmornati/mock-rpmbuilder"
    - if [ -n "$TRAVIS_TAG" ]; then
      image="$image:$TRAVIS_TAG";
      fi
    - docker build -t "$image" .
    - docker inspect "$image"
    - docker run --rm --name mocktest "$image" su - builder -c "/usr/sbin/mock --version"
script:
        - official-images/test/run.sh -t utc -t override-cmd "$image"

after_script:
    - docker images

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$image";
